version: 0.2

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - echo $ACCOUNT_ID
      - echo "Login to Amazon ECR"
      - aws --version
      - echo "$(aws ecr get-login-password --region ap-northeast-1)" | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - docker build -t school_of_movie_api:latest .
      - docker tag school_of_movie_api:latest $ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/school_of_movie_api:$IMAGE_TAG
  post_build:
    commands:
      - docker push $ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/school_of_movie_api:$IMAGE_TAG
