version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: funny_cats_api_development
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec solargraph socket --host=0.0.0.0 --port=7658 && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/funny_cats_api/
    ports:
      - 3000:3000
      - 8091:7658
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      REDIS_URL: redis:6379
  minio:
    image: 'minio/minio'
    container_name: minio
    environment:
        MINIO_ROOT_USER: user
        MINIO_ROOT_PASSWORD: 123456789o
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
        - ./docker/minio/data:/export
    ports:
        - '9000:9000'
        - '9001:9001'
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/export
volumes:
  mysql_data:
  minio:
    driver: local