development:
  adapter: async
  url: redis://redis:6379/0/cache

test:
  adapter: test
  url: redis://redis:6379/0/cache

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: funny_cats_api_production
