development:
  adapter: async
  url: redis://redis:6379/0/cache

test:
  adapter: test
  url: redis://<%= ENV.fetch("REDIS_HOST") { "redis:6379" } %>/0/cache

production:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_HOST") { "redis:6379" } %>/0/cache
  channel_prefix: school_of_movie_api_production
